using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace CartographeAutomatique;

public enum MappingStrategyInternal
{
    Constructor,
    Setter
}

internal class TypeMapping(
    TypeDeclarationSyntax sourceType,
    TypeDeclarationSyntax targetType,
    bool exhaustive,
    MappingStrategyInternal strategy,
    GeneratorSyntaxContext context)
{
    public string GenerateMapping()
    {
        var activeStrategy = TargetIsRecord() switch
        {
            true => MappingStrategyInternal.Constructor,
            _ => strategy
        };

        var assignations = GenerateAssignation(activeStrategy);
        var sourceNameSpace = SourceNameSpace()!;
        var targetNameSpace = TargetNameSpace()!;

        var joinedAssignation = activeStrategy switch
        {
            MappingStrategyInternal.Setter => string.Join(",\n\t\t\t", assignations),
            MappingStrategyInternal.Constructor => string.Join(",", assignations),
        };

        var instantiation = activeStrategy switch
        {
            MappingStrategyInternal.Setter => $"\tnew()\n\t\t{{\n\t\t\t{joinedAssignation}\n\t\t}};",
            MappingStrategyInternal.Constructor => $"\tnew({joinedAssignation});",
        };

        return $$"""
                 // <auto-generated/>
                 namespace {{sourceNameSpace}};

                 public static partial class {{SourceClassName}}MappingExtensions
                 {
                     public static {{targetNameSpace}}.{{TargetClassName}} MapTo{{TargetClassName}}(this {{SourceClassName}} source) =>
                        {{instantiation}}
                 }
                 """;
    }

    public string SourceClassName => sourceType.Identifier.Text;
    public string TargetClassName => targetType.Identifier.Text;


    private List<string> GenerateAssignation(MappingStrategyInternal activeStrategy)
    {
        List<string> assignations = [];

        var sourceProperties = GetSourceProperties();

        if (sourceProperties == null) return assignations;

        foreach (var prop in sourceProperties)
        {
            var customMethod = prop.WithMethod();
            string? methodName = null;

            if (customMethod != null)
            {
                var constantValue = context.SemanticModel.GetConstantValue(customMethod.Expression);
                if (constantValue is { HasValue: true, Value: string methodNameValue })
                {
                    methodName = methodNameValue;
                }
            }

            var targetField = prop.TargetField();
            var targetFieldName = prop.Identifier;

            if (targetField != null)
            {
                var constantValue = context.SemanticModel.GetConstantValue(targetField.Expression);
                if (constantValue is { HasValue: true, Value: string targetMappingFieldName })
                {
                    targetFieldName = targetMappingFieldName;
                }
            }

            var targetProp = GetMatchingTargetProp(targetFieldName, activeStrategy);


            if (targetProp is null)
            {
                if (exhaustive is false)
                    continue;

                throw new Exception("invalid mapping");
            }

            var propertyTypeSymbol = targetProp.Type.GetPropertyTypeSymbol(context);

            var assignation = activeStrategy switch
            {
                MappingStrategyInternal.Constructor when methodName is not null =>
                    $"""{targetProp.Identifier}: {methodName}(source.{prop.Identifier})""",
                MappingStrategyInternal.Setter when methodName is not null =>
                    $"""{targetProp.Identifier} = {methodName}(source.{prop.Identifier})""",
                MappingStrategyInternal.Constructor => !propertyTypeSymbol!.IsPrimitiveType()
                    ? $"""{targetProp.Identifier}: source.{prop.Identifier}.MapTo{propertyTypeSymbol!.Name}()"""
                    : $"""{targetProp.Identifier}: source.{prop.Identifier}""",
                MappingStrategyInternal.Setter => !propertyTypeSymbol!.IsPrimitiveType()
                    ? $"""{targetProp.Identifier} = source.{prop.Identifier}.MapTo{propertyTypeSymbol!.Name}()"""
                    : $"""{targetProp.Identifier} = source.{prop.Identifier}""",
                _ => throw new ArgumentOutOfRangeException(),
            };

            assignations.Add(assignation);
        }

        return assignations;
    }

    private PropertyOrParameter? GetMatchingTargetProp(string targetFieldName, MappingStrategyInternal activeStrategy)
    {
        if (targetType is ClassDeclarationSyntax targetClass && activeStrategy == MappingStrategyInternal.Constructor)
        {
            var constructor = targetClass.Members
                .OfType<ConstructorDeclarationSyntax>()
                .OrderByDescending(c => c.ParameterList.Parameters.Count) // Sort by parameter count
                .FirstOrDefault();

            return constructor?.ParameterList?
                .Parameters
                .Select(targetParameter =>
                    new PropertyOrParameter(targetParameter.Type, targetParameter.Identifier.Text))
                .SingleOrDefault(targetParameter => targetParameter.Identifier == targetFieldName);
        }

        return targetType switch
        {
            ClassDeclarationSyntax classDeclaration => classDeclaration.Members
                .OfType<PropertyDeclarationSyntax>()
                .Select(targetParameter =>
                    new PropertyOrParameter(targetParameter.Type, targetParameter.Identifier.Text))
                .SingleOrDefault(targetProperty => targetProperty.Identifier == targetFieldName),

            RecordDeclarationSyntax recordDeclaration => recordDeclaration.ParameterList?
                .Parameters
                .Select(targetParameter =>
                    new PropertyOrParameter(targetParameter.Type, targetParameter.Identifier.Text))
                .SingleOrDefault(targetParameter => targetParameter.Identifier == targetFieldName),
            _ => throw new NotImplementedException()
        };
    }

    private IEnumerable<PropertyOrParameter>? GetSourceProperties() =>
        sourceType switch
        {
            ClassDeclarationSyntax sourceClass => sourceClass.Members
                .OfType<PropertyDeclarationSyntax>()
                .Select(member =>
                    (Member: member, Attribute: member.GetMatchingMappingAttribute(TargetClassName)))
                .Select(type =>
                    new PropertyOrParameter(type.Member.Type, type.Member.Identifier.Text, type.Attribute)),

            RecordDeclarationSyntax sourceRecord => sourceRecord
                .ParameterList?
                .Parameters
                .ToList()
                .Select(parameter => (Parameter: parameter,
                    Attribute: parameter.GetMatchingMappingAttribute(TargetClassName)))
                .Select(type =>
                    new PropertyOrParameter(type.Parameter.Type, type.Parameter.Identifier.Text, type.Attribute)),
            _ => throw new ArgumentOutOfRangeException(nameof(sourceType), sourceType, null)
        };

    private string? TargetNameSpace()
    {
        if (context.SemanticModel.GetDeclaredSymbol(targetType) is not INamedTypeSymbol sourceClassSymbol)
            return null;

        return sourceClassSymbol.ContainingNamespace.ToDisplayString();
    }

    private string? SourceNameSpace()
    {
        if (context.SemanticModel.GetDeclaredSymbol(sourceType) is not INamedTypeSymbol sourceClassSymbol)
            return null;

        return sourceClassSymbol.ContainingNamespace.ToDisplayString();
    }

    private bool TargetIsRecord() => targetType is RecordDeclarationSyntax;
}