using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace CartographeAutomatique;

public enum MappingStrategyInternal
{
    Constructor,
    Setter
}

internal class TypeMapping(
    TypeDeclarationSyntax sourceType,
    TypeDeclarationSyntax targetType,
    bool exhaustive,
    MappingStrategyInternal strategy,
    GeneratorSyntaxContext context)
{
    public string GenerateMapping()
    {
        var activeStrategy = TargetIsRecord() switch
        {
            true => MappingStrategyInternal.Constructor,
            _ => strategy
        };

        var assignations = GenerateAllAssignation(activeStrategy);
        var sourceNameSpace = SourceNameSpace()!;
        var targetNameSpace = TargetNameSpace()!;

        var joinedAssignation = activeStrategy switch
        {
            MappingStrategyInternal.Setter => string.Join(",\n\t\t\t", assignations),
            MappingStrategyInternal.Constructor => string.Join(",", assignations),
            _ => throw new ArgumentOutOfRangeException()
        };

        var instantiation = activeStrategy switch
        {
            MappingStrategyInternal.Setter => $"\tnew()\n\t\t{{\n\t\t\t{joinedAssignation}\n\t\t}};",
            MappingStrategyInternal.Constructor => $"\tnew({joinedAssignation});",
            _ => throw new ArgumentOutOfRangeException()
        };

        return $$"""
                 // <auto-generated/>
                 namespace {{sourceNameSpace}};

                 public static partial class {{SourceClassName}}MappingExtensions
                 {
                     public static {{targetNameSpace}}.{{TargetClassName}} MapTo{{TargetClassName}}(this {{SourceClassName}} source) =>
                        {{instantiation}}
                 }
                 """;
    }

    public string SourceClassName => sourceType.Identifier.Text;
    public string TargetClassName => targetType.Identifier.Text;


    private List<string> GenerateAllAssignation(MappingStrategyInternal activeStrategy) =>
        (GetSourceProperties() ?? Array.Empty<PropertyOrParameter>())
        .Select(prop => GenerateAssignation(activeStrategy, prop))
        .Where(prop => prop != null)
        .Select(prop => prop!)
        .ToList();

    private string? GenerateAssignation(MappingStrategyInternal activeStrategy, PropertyOrParameter sourceProp)
    {
        var customMethod = sourceProp.WithMethod();
        string? methodName = null;

        if (customMethod != null)
        {
            var constantValue = context.SemanticModel.GetConstantValue(customMethod.Expression);
            if (constantValue is { HasValue: true, Value: string methodNameValue })
            {
                methodName = $"{methodNameValue}(source.{sourceProp.Identifier})";
            }
        }

        var targetField = sourceProp.TargetField();
        var targetFieldName = sourceProp.Identifier;

        if (targetField != null)
        {
            var constantValue = context.SemanticModel.GetConstantValue(targetField.Expression);
            if (constantValue is { HasValue: true, Value: string targetMappingFieldName })
            {
                targetFieldName = targetMappingFieldName;
            }
        }

        var targetProp = GetMatchingTargetProp(targetFieldName, activeStrategy);


        if (targetProp is null)
        {
            if (exhaustive is false)
                return null;

            throw new Exception("invalid mapping");
        }

        var targetTypeSymbol = targetProp.Type.GetPropertyTypeSymbol(context);
        var sourceTypeSymbol = sourceProp.Type.GetPropertyTypeSymbol(context);

        var maybeListConvertion = ListConversion(sourceProp, targetTypeSymbol, sourceTypeSymbol);

        string? implicitConversion = null;
        if (customMethod is null)
        {
            implicitConversion = GetImplicitConversion(sourceProp.Identifier, targetTypeSymbol, sourceTypeSymbol);
        }

        var lhs = activeStrategy switch
        {
            MappingStrategyInternal.Constructor => $"{targetProp.Identifier}: ",
            MappingStrategyInternal.Setter => $"{targetProp.Identifier} = ",
            _ => throw new ArgumentOutOfRangeException(nameof(activeStrategy), activeStrategy, null)
        };

        var rhs = implicitConversion ?? methodName ?? maybeListConvertion ?? (!targetTypeSymbol!.IsPrimitiveType()
            ? $"source.{sourceProp.Identifier}.MapTo{targetTypeSymbol!.Name}()"
            : $"source.{sourceProp.Identifier}");

        return $"{lhs}{rhs}";
    }

    private static string? ListConversion(PropertyOrParameter sourceProp, INamedTypeSymbol? targetTypeSymbol,
        INamedTypeSymbol? sourceTypeSymbol)
    {
        string? maybeListConvertion = null;
        if (!targetTypeSymbol.IsCollection1() || !sourceTypeSymbol.IsCollection1()) return maybeListConvertion;
        
        var sourceGenericParameter = sourceTypeSymbol!.FirstGenericParameterName();
        var targetGenericParameter = targetTypeSymbol!.FirstGenericParameterName();
        var hasSameGenericParameter = sourceGenericParameter.Name == targetGenericParameter.Name
                                      && sourceGenericParameter.ContainingNamespace
                                          .ToDisplayString() == targetGenericParameter.ContainingNamespace
                                          .ToDisplayString();

        // TODO: Here we need to handle case where the generic parameter is the same but the collection type should be mapped
        if (hasSameGenericParameter) return null;

        var listMemberConversion = (targetTypeSymbol!.Name, sourceTypeSymbol!.Name) switch
        {
            ("List", "List") =>
                GetImplicitConversion("i", targetGenericParameter, sourceGenericParameter)
                ?? $"i.MapTo{targetGenericParameter!.Name}()",
            // Todo : 
            _ => throw new NotImplementedException()
        };

        maybeListConvertion = $"source.{sourceProp.Identifier}.Select(i => {listMemberConversion}).ToList()";

        return maybeListConvertion;
    }

    private static string? GetImplicitConversion(string sourcePropIdentifier, ITypeSymbol? targetType,
        ITypeSymbol? sourceType)
    {
        var sourceMemberAccess = $"source.{sourcePropIdentifier}";
        // var sourceIsCollection = sourceType?.AllInterfaces.Any(i => i.Name is "IEnumerable`1" or "ICollection`1");
        //  var targetIsCollection = targetType?.AllInterfaces.Any(i => i.Name is "IEnumerable`1" or "ICollection`1");
        var implicitMapping = (sourceType?.SpecialType, targetType?.SpecialType) switch
        {
            (SpecialType.System_String, SpecialType.System_Single) => $"Single.Parse({sourceMemberAccess})",
            (SpecialType.System_String, SpecialType.System_Int16) => $"Int16.Parse({sourceMemberAccess})",
            (SpecialType.System_String, SpecialType.System_Int32) => $"Int32.Parse({sourceMemberAccess})",
            (SpecialType.System_String, SpecialType.System_Int64) => $"Int64.Parse({sourceMemberAccess})",
            (SpecialType.System_String, SpecialType.System_UInt16) => $"Int16.Parse({sourceMemberAccess})",
            (SpecialType.System_String, SpecialType.System_UInt32) => $"UInt32.Parse({sourceMemberAccess})",
            (SpecialType.System_String, SpecialType.System_UInt64) => $"UInt64.Parse({sourceMemberAccess})",
            (SpecialType.System_Single, SpecialType.System_String) or
                (SpecialType.System_Int16, SpecialType.System_String) or
                (SpecialType.System_Int32, SpecialType.System_String) or
                (SpecialType.System_Int64, SpecialType.System_String) or
                (SpecialType.System_UInt16, SpecialType.System_String) or
                (SpecialType.System_UInt32, SpecialType.System_String) or
                (SpecialType.System_String, SpecialType.System_Enum) or
                (SpecialType.System_UInt64, SpecialType.System_String) =>
                $"{sourceMemberAccess}.ToString(System.Globalization.CultureInfo.InvariantCulture)",
            _ => null
            // If no special type were found fallback to name comparison 
            // The example below is not working as we probably need to find a way
            // To extract Generic parameter for collections (or pass the generic parameter in this method call).
            // This needs further exploration in the ITypeSymbol public API.
        } ?? (targetType?.Name, sourceType?.Name) switch
        {
            ("List<MyType>", "MyType[]") => $"ToString()",
            _ => null
        };

        return implicitMapping;
    }

    private PropertyOrParameter? GetMatchingTargetProp(string targetFieldName, MappingStrategyInternal activeStrategy)
    {
        if (targetType is ClassDeclarationSyntax targetClass && activeStrategy == MappingStrategyInternal.Constructor)
        {
            var constructor = targetClass.Members
                .OfType<ConstructorDeclarationSyntax>()
                .OrderByDescending(c => c.ParameterList.Parameters.Count) // Sort by parameter count
                .FirstOrDefault();

            return constructor?.ParameterList.Parameters
                .Select(targetParameter =>
                    new PropertyOrParameter(targetParameter.Type, targetParameter.Identifier.Text,
                        GetGenericTypeArguments(targetParameter)))
                .SingleOrDefault(targetParameter => targetParameter.Identifier == targetFieldName);
        }

        return targetType switch
        {
            ClassDeclarationSyntax classDeclaration => classDeclaration.Members
                .OfType<PropertyDeclarationSyntax>()
                .Select(targetParameter =>
                    new PropertyOrParameter(targetParameter.Type, targetParameter.Identifier.Text,
                        GetGenericTypeArguments(targetParameter)))
                .SingleOrDefault(targetProperty => targetProperty.Identifier == targetFieldName),

            RecordDeclarationSyntax recordDeclaration => recordDeclaration.ParameterList?
                .Parameters
                .Select(targetParameter =>
                    new PropertyOrParameter(targetParameter.Type, targetParameter.Identifier.Text,
                        GetGenericTypeArguments(targetParameter)))
                .SingleOrDefault(targetParameter => targetParameter.Identifier == targetFieldName),
            _ => throw new ArgumentOutOfRangeException()
        };
    }

    private IEnumerable<PropertyOrParameter>? GetSourceProperties() =>
        sourceType switch
        {
            ClassDeclarationSyntax sourceClass => sourceClass.Members
                .OfType<PropertyDeclarationSyntax>()
                .Select(member =>
                    (Member: member, Attribute: member.GetMatchingMappingAttribute(TargetClassName)))
                .Select(type =>
                    new PropertyOrParameter(type.Member.Type, type.Member.Identifier.Text,
                        GetGenericTypeArguments(type.Member), type.Attribute)),

            RecordDeclarationSyntax sourceRecord => sourceRecord
                .ParameterList?
                .Parameters
                .ToList()
                .Select(parameter => (Parameter: parameter,
                    Attribute: parameter.GetMatchingMappingAttribute(TargetClassName)))
                .Select(type =>
                    new PropertyOrParameter(type.Parameter.Type, type.Parameter.Identifier.Text,
                        GetGenericTypeArguments(type.Parameter), type.Attribute)),
            _ => throw new ArgumentOutOfRangeException(nameof(sourceType), sourceType, null)
        };

    private string? TargetNameSpace()
    {
        if (context.SemanticModel.GetDeclaredSymbol(targetType) is not INamedTypeSymbol sourceClassSymbol)
            return null;

        return sourceClassSymbol.ContainingNamespace.ToDisplayString();
    }

    private string? SourceNameSpace()
    {
        if (context.SemanticModel.GetDeclaredSymbol(sourceType) is not INamedTypeSymbol sourceClassSymbol)
            return null;

        return sourceClassSymbol.ContainingNamespace.ToDisplayString();
    }

    private bool TargetIsRecord() => targetType is RecordDeclarationSyntax;


    private ImmutableArray<ITypeSymbol>? GetGenericTypeArguments(PropertyDeclarationSyntax propertyDeclarationSyntax)
    {
        if (context.SemanticModel.GetDeclaredSymbol(propertyDeclarationSyntax) is not IPropertySymbol propertySymbol)
        {
            return null;
        }

        if (propertySymbol.Type is not INamedTypeSymbol { IsGenericType: true } namedType) return null;
        var genericArguments = namedType.TypeArguments;
        return genericArguments;
    }

    private ImmutableArray<ITypeSymbol>? GetGenericTypeArguments(ParameterSyntax parameterSyntax)
    {
        if (context.SemanticModel.GetDeclaredSymbol(parameterSyntax) is not IParameterSymbol propertySymbol)
        {
            return null;
        }

        if (propertySymbol.Type is not INamedTypeSymbol { IsGenericType: true } namedType) return null;
        var genericArguments = namedType.TypeArguments;
        return genericArguments;
    }
}