namespace CartographeAutomatique.Tests;

public class RecordSourceTypeSingleMember : IFixture
{
    private const string Source =
        //language=csharp
        """
        namespace TestNamespace;

        public record A(string C);

        [CartographeAutomatique.MapTo(typeof(TestNamespace.A))]
        public class B
        {
        
            public C C { get; set; }
        }

        public record C(string Inner);
        """;

    private const string Expected =
        //language=csharp
        """
        // <auto-generated/>
        namespace TestNamespace;

        public static partial class BMappingExtensions
        {
            public static TestNamespace.A MapToA(this TestNamespace.B source) =>
               	new(C: source.C.Inner);
        }
        """;

    public SourceGenerationAssertion GetAssertion() =>
        new(Source, [new SourceGenerationOutput("TestNamespace_BToTestNamespace_A", Expected)]);
}