namespace CartographeAutomatique.Tests;

public class RecordToRecord : IFixture
{
    private const string Source =
        //language=csharp
        """
            namespace TestNamespace;
            using CartographeAutomatique;

            [MapTo(typeof(HexColor))]
            public record Color([Mapping(TargetType = typeof(HexColor), TargetField = "HexValue")] string Value);

            public record HexColor(string HexValue);
            """;

    private const string Expected =
        //language=csharp
        """
            // <auto-generated/>
            namespace TestNamespace;

            public static partial class ColorMappingExtensions
            {
                public static TestNamespace.HexColor MapToHexColor(this TestNamespace.Color source) =>
                   	new(HexValue: source.Value);
            }
            """;

    public SourceGenerationAssertion GetAssertion() =>
        new(Source, [new("ColorToHexColor", Expected)]);
}
