namespace CartographeAutomatique.Tests;

public class RecordToClass : IFixture
{
    private const string Source =
        //language=csharp
        """
        namespace TestNamespace;
        using Generators;
        
        [MapTo(typeof(Truck))]
        internal record Car(string Color, string Brand);

        internal class Truck
        {
            public string Color { get; set; }
            public string Brand { get; set; }
        };
        """;
    private const string Expected =
        //language=csharp
        """
        // <auto-generated/>
        namespace TestNamespace;

        public static partial class CarMappingExtensions
        {
            public static TestNamespace.Truck MapToTruck(this Car source) =>
               	new()
        		{
        			Color = source.Color,
        			Brand = source.Brand
        		};
        }
        """;

    public SourceGenerationAssertion GetAssertion() =>
        new(Source,
            [new("CarToTruck", Expected)]);
}